<?php
$MAC = array (
  'db' => 
  array (
    'type' => 'mysqli',
    'path' => '',
    'server' => '127.0.0.1',
    'port' => '3306',
    'name' => 'maccms8',
    'user' => 'root',
    'pass' => 'root',
    'tablepre' => 'mac_',
  ),
  'site' => 
  array (
    'name' => '免费短视频分享大全 - 大中国',
    'installdir' => '/',
    'url' => 'www.test.cn',
    'keywords' => '短视频,搞笑视频,视频分享,免费视频,在线视频,预告片',
    'description' => '提供最新最快的视频分享数据',
    'templatedir' => 'default',
    'htmldir' => 'html',
    'adsdir' => 'ads',
    'icp' => 'icp123',
    'email' => '123456@test.com',
    'qq' => '123456',
    'tj' => '统计代码',
    'mobstatus' => '1',
    'mobtemplatedir' => 'default',
    'mobhtmldir' => 'html',
  ),
  'app' => 
  array (
    'cachetype' => 0,
    'cache' => 0,
    'dynamiccache' => 0,
    'cachetime' => 60,
    'cacheid' => 'abcdefghigk',
    'memcachedhost' => '127.0.0.1',
    'memcachedport' => '11211',
    'safecode' => 'maccms',
    'pagesize' => 18,
    'expandtype' => 0,
    'playersort' => 0,
    'area' => '大陆,香港,台湾,美国,韩国,日本,泰国,新加坡,马来西亚,印度,英国,法国,加拿大,西班牙,俄罗斯,其它',
    'lang' => '国语,英语,粤语,闽南语,韩语,日语,法语,德语,其它',
    'suffix' => 'html',
    'maketime' => '2',
    'makesize' => '20',
    'isopen' => 0,
    'encrypt' => 1,
    'compress' => 0,
    'searchtime' => 5,
    'filtertags' => 2,
    'searchlen' => 10,
    'memcacheduser' => '',
    'memcachedpass' => '',
  ),
  'view' => 
  array (
    'vodindex' => 0,
    'vodmap' => 0,
    'vodlist' => 0,
    'vodtype' => 0,
    'vodtopicindex' => 0,
    'vodtopic' => 0,
    'voddetail' => 0,
    'vodplay' => 0,
    'voddown' => 0,
    'vodsearch' => 0,
    'artindex' => 0,
    'artmap' => 0,
    'artlist' => 0,
    'arttype' => 0,
    'arttopicindex' => 0,
    'arttopic' => 0,
    'artdetail' => 0,
    'artsearch' => 0,
    'gbook' => 0,
    'rss' => 0,
    'label' => 0,
  ),
  'path' => 
  array (
    'vodindex' => 'index',
    'vodmap' => 'vodmap',
    'vodtype' => 'vodtypehtml/{id}',
    'vodtopicindex' => 'vodtopicindex',
    'vodtopic' => 'vodtopichtml/{id}',
    'voddetail' => 'vodhtml/{id}',
    'vodplay' => 'vodplayhtml/{id}',
    'voddown' => 'voddownhtml/{id}',
    'artindex' => 'artindex',
    'artmap' => 'artmap',
    'arttype' => 'arttypehtml/{id}',
    'arttopicindex' => 'arttopicindex',
    'arttopic' => 'arttopichtml/{id}',
    'artdetail' => 'arthtml/{id}',
  ),
  'rewrite' => 
  array (
    'vodindex' => 'index-pg-{pg}',
    'vodmap' => 'vod-map',
    'vodlist' => 'vod-list-id-{id}-pg-{pg}-order-{order}-by-{by}-class-{class}-year-{year}-letter-{letter}-area-{area}-lang-{lang}',
    'vodtype' => 'vod-type-id-{id}-pg-{pg}',
    'vodtopicindex' => 'vod-topicindex-pg-{pg}',
    'vodtopic' => 'vod-topic-id-{id}-pg-{pg}',
    'voddetail' => 'vod-detail-id-{id}',
    'vodplay' => 'vod-play-id-{id}-src-{src}-num-{num}',
    'voddown' => 'vod-down-id-{id}-src-{src}-num-{num}',
    'vodsearch' => 'vod-search-pg-{pg}-wd-{wd}',
    'artindex' => 'art-index-pg-{pg}',
    'artmap' => 'art-map',
    'artlist' => 'art-list-id-{id}-pg-{pg}-order-{order}-by-{by}',
    'arttype' => 'art-type-id-{id}-pg-{pg}',
    'arttopicindex' => 'art-topicindex-pg-{pg}',
    'arttopic' => 'art-topic-id-{id}-pg-{pg}',
    'artdetail' => 'art-detail-id-{id}-pg-{pg}',
    'artsearch' => 'art-search-pg-{pg}-wd-{wd}',
    'gbook' => 'gbook-show-pg-{pg}',
    'rss' => 'map-{method}-pg-{pg}',
    'label' => 'label-{label}-pg-{pg}',
  ),
  'user' => 
  array (
    'status' => 1,
    'reg' => 1,
    'regpoint' => 1,
    'regstate' => 1,
    'popularize' => 2,
    'popularizestate' => 1,
    'reggroup' => 1,
    'weekpoint' => 100,
    'monthpoint' => 1000,
    'yearpoint' => 5000,
  ),
  'other' => 
  array (
    'filter' => 'http,//,com,cn,net,org,www',
    'gbook' => 1,
    'gbooknum' => 10,
    'gbooktime' => 10,
    'gbookverify' => 1,
    'gbookaudit' => 0,
    'comment' => 1,
    'commentnum' => 10,
    'commenttime' => 10,
    'commentverify' => 1,
    'commentaudit' => 0,
    'mood' => 0,
  ),
  'upload' => 
  array (
    'thumb' => 0,
    'thumbw' => 110,
    'thumbh' => 150,
    'picpath' => 0,
    'watermark' => 0,
    'waterlocation' => 0,
    'waterfont' => 'test',
    'remote' => 0,
    'remoteurl' => 'http://img.test.com/',
    'ftp' => 0,
    'ftphost' => 'img.test.com',
    'ftpuser' => 'user',
    'ftppass' => 'pass',
    'ftpdir' => '/wwwroot/',
    'ftpport' => '21',
    'ftpdel' => 0,
    'filter' => '*.jpg;*.jpeg;*.gif;*.png;*.bmp;*.zip;*.rar;*.txt;*.torrent',
  ),
  'interface' => 
  array (
    'pass' => 'EN13PNZP6C',
  ),
  'pay' => 
  array (
    'app' => 
    array (
      'min' => 10,
      'exc' => 1,
    ),
    'alipay' => 
    array (
      'no' => 'master@test.com',
      'id' => '888888',
      'key' => '000000',
    ),
    'ys' => 
    array (
      'id' => '201238303611',
      'key' => 'wxkhhbr8x9aew6c6',
    ),
  ),
  'collect' => 
  array (
    'vod' => 
    array (
      'key' => '111',
      'hitsstart' => 1,
      'hitsend' => 1000,
      'hide' => 0,
      'pic' => 0,
      'psernd' => 0,
      'psesyn' => 0,
      'inrule' => ',0',
      'uprule' => ',a,j',
      'filter' => '色戒,色即是空',
      'tag' => 0,
      'score' => 0,
    ),
    'art' => 
    array (
      'key' => '222',
      'hitsstart' => 1,
      'hitsend' => 1000,
      'hide' => 0,
      'pic' => 0,
      'psernd' => 0,
      'psesyn' => 0,
      'inrule' => ',0',
      'uprule' => ',a',
      'filter' => '无奈的人',
      'tag' => 1,
    ),
  ),
  'api' => 
  array (
    'vod' => 
    array (
      'status' => 0,
      'imgurl' => 'http://img.test.com/',
      'typefilter' => 'and t_hide=0',
      'vodfilter' => 'and d_hide=0',
      'pagesize' => 20,
      'cjflag' => '',
      'charge' => '0',
      'auth' => 'test.com#163.com',
    ),
    'art' => 
    array (
      'status' => 0,
      'cjflag' => '',
      'imgurl' => '{art_imgurl}',
      'typefilter' => '{art_typefilter}',
      'vodfilter' => '{art_vodfilter}',
      'pagesize' => 20,
      'charge' => '0',
      'auth' => '{art_auth}',
    ),
  ),
  'connect' => 
  array (
    'qq' => 
    array (
      'status' => 0,
      'id' => '11',
      'key' => '22',
    ),
    'uc' => 
    array (
      'status' => 0,
      'id' => '',
      'key' => '',
      'url' => '',
      'dbhost' => '',
      'dbuser' => '',
      'dbpass' => '',
      'dbname' => '',
      'dbpre' => '',
      'ip' => '',
    ),
  ),
  'weixin' => 
  array (
    'duijie' => 'wx.test.com',
    'sousuo' => 'wx.test.com',
    'token' => 'qweqwe',
    'guanzhu' => '欢迎关注',
    'wuziyuan' => '没找到资源，请更换关键词或等待更新',
    'wuziyuanlink' => 'demo.test.com',
    'bofang' => '1',
    'gjc1' => '关键词1',
    'gjcm1' => '长城',
    'gjci1' => 'http://img.aolusb.com/im/201610/2016101222371965996.jpg',
    'gjcl1' => 'http://www.loldytt.com/Dongzuodianying/CC/',
    'gjc2' => '关键词2',
    'gjcm2' => '生化危机6',
    'gjci2' => 'http://img.aolusb.com/im/201702/20172711214866248.jpg',
    'gjcl2' => 'http://www.loldytt.com/Kehuandianying/SHWJ6ZZ/',
    'gjc3' => '关键词3',
    'gjcm3' => '湄公河行动',
    'gjci3' => 'http://img.aolusb.com/im/201608/201681719561972362.jpg',
    'gjcl3' => 'http://www.loldytt.com/Dongzuodianying/GHXD/',
    'gjc4' => '关键词4',
    'gjcm4' => '王牌逗王牌',
    'gjci4' => 'http://img.aolusb.com/im/201601/201612723554344882.jpg',
    'gjcl4' => 'http://www.loldytt.com/Xijudianying/WPDWP/',
  ),
);
?>